### ISSUE TITLE
US1 - landing page

### ISSUE THREAD

**Issue by Steffen-Anslinger** [Steffen-Anslinger/DIY-App#1]
## Value proposition
As a diy enthusiast
i want to see a list of projects
so that i can have an overview of different projects to get some inspiration
## Description
![Mittel (User Story 1)](https://github.com/Steffen-Anslinger/DIY-App/assets/149775085/428fbcfa-5f6b-44b2-ab1e-91bbf5fb523e)
## Acceptance criteria
- [ ] the Header should be displayed on top of the Page
- [ ] all projects should be displayed as a list
- [ ] each project image is displayed
- [ ] each project title is displayed
## Tasks
- [ ] create a Header Component and place it on top on the page
- [ ] create the component Projects to render a list
- [ ] Create the component ProjectPreview

**Comment by CJAkkuec** [comment]
Nice job! Straight forward user story covering all bases.
You only forgot to mention the Header components as part of the AC and tasks. 👀

**Comment by JuliaSchw** [comment]
update 1 ✅

**Comment by franziska-caroline** [comment]
Hello diy app team :)
Great idea with the app! 
I have a few comments on your user story.

In the value proposition, I would stick to the correct form. Maybe something like this: 
As a diy enthusiast
i want to see a list of projects
so that i can have an overview of different projects to get some inspiration
