### ISSUE TITLE
US10 - Change order projects view Homepage

### ISSUE THREAD

**Issue by MaikBerdelmann** [Steffen-Anslinger/DIY-App#14]
## Value proposition

As a user
I want to see the newest created project on top of the homepage
so that i can see new ideas first

## Description

The newest projects will be shown on the top of the screen. They will be sorted by a timestamp.

## Acceptance criteria

- [ ] The first project is the newest created
- [ ] After creation of a new project it appears on top.

## Tasks

- [ ] implement the sort function
- [ ] add a timestamp to each entry

**Comment by F-Kirchhoff** [comment]
LGTM 🚀
