### ISSUE TITLE
US11 - Design Project View

### ISSUE THREAD

**Issue by MaikBerdelmann** [Steffen-Anslinger/DIY-App#15]
## Value proposition

As a user...
I want to have a minimalisitc and modern designed view on the Projects on the homepage, 
so that it’s easier for me to process what I see.

## Description

![Image](https://github.com/Steffen-Anslinger/DIY-App/assets/149384055/00d2cb21-0af4-4d6f-92c9-47ad7c59dd8d)

## Acceptance criteria

- [ ] i want to see the Project card with Image, Title, Duration, Difficulty - on the homepage
- [ ] i want to see a grid view with multiple columns depending on screen size - Masonry View - for the homepage

## Tasks

- [ ] Styled Component for Project Card on the homepage
- [ ] Styled Component for Project View [ ] implement `masonry`

**Comment by F-Kirchhoff** [comment]
Hey Maik, 
in this US, do you want to style the entire app or just the homepage?

**Comment by Steffen-Anslinger** [comment]
Hi Felix, Thank you for your comment.
We only meant to style the projectlist on the homepage in this US. 
I updated it accordingly :)

**Comment by F-Kirchhoff** [comment]
alright then it LGTM 👍
