### ISSUE TITLE
US12 - Update Search Bar with filter function

### ISSUE THREAD

**Issue by MaikBerdelmann** [Steffen-Anslinger/DIY-App#16]
## Value proposition

As a user
I want to have the option to filter all projects on the homepage
so that i can easy find projects.

## Description

![Image](https://github.com/Steffen-Anslinger/DIY-App/assets/149775085/bf0ef235-3131-442d-9a43-5fa487e445db)

## Acceptance criteria

- [ ] I want to see a filter menu next to the search bar 
- [ ] by clicking on the filter button the filter section should open 
- [ ] the filter section should include difficulty, duration
- [ ] i want to have the option to reset all filters with one click
- [ ] Each filter can be deleted/reseted individually
- [ ] The filtering will be activated as live search

## Tasks
- [ ] implement the filter function
- [ ] create a Filter Section Component
- [ ] create filter button that opens the filter by clicking
- [ ] set up filters that filter data based on a category (duration, difficulty)
- [ ] create filter section as form fields
- [ ] add filter reset buttons

**Comment by F-Kirchhoff** [comment]
Hey,
please specify the behavior when the filter is applied. Is it directly after I choose a value for a filter? And how can I reset one filter but not the other ones? And please give a bit more context in the Tasks, the filter section should be a form, so please specify that too.
