### ISSUE TITLE
US4 - Details Page

### ISSUE THREAD

**Issue by MaikBerdelmann** [Steffen-Anslinger/DIY-App#2]
## Value proposition
As a user 
I want to be able to see the full project with detail information
so that I can learn everything about the project.

## Description
![Image](https://github.com/Steffen-Anslinger/DIY-App/assets/149384055/8ef1183d-93cd-4d8d-a305-946cb6a178f5)

## Acceptance criteria
- [ ] The project image is displayed
- [ ] The project title is displayed
- [ ] The project description is displayed
- [ ] The Duration is displayed
- [ ] The Difficulty is displayed
- [ ] The project material list is displayed
- [ ] The project work steps are displayed
- [ ] A back-button is displayed to return to homepage
- [ ] Clicking the back-button shows the list view
## Tasks
- [ ] Create the component ProjectDetails
- [ ] Create the page pages/projects/[slug] that renders ProjectsDetails
- [ ] Create the back button and link to homepage
- [ ] Read the query parameter slug from next/router
- [ ] Use the slug to find the project
 to display

**Comment by CJAkkuec** [comment]
Very good - nothing _needs_ to be changed, but perhaps keep in kind that the intended behavior of the AC is best described as a sentence, such as "When the user clicks the back button, the user is routed back to the overview page".
