### ISSUE TITLE
US13 - Accessibility

### ISSUE THREAD

**Issue by MaikBerdelmann** [Steffen-Anslinger/DIY-App#21]
## Value proposition

As a disabled user... 
i want to be able to access all sites and data.

## Description

We want to create an App that can use everybody. So we decided to implement some Accessibility features to your App.

## Acceptance criteria

- [ ] all interactive elements of the user interface are provided with clear and informative text for screen readers
- [ ] all controls can be operated using the keyboard or other input devices
- [ ] forms are logically structured and include descriptions for each form field
- [ ] images and multimedia content have alternative texts

## Tasks

- [ ] add aria labels
- [ ] implement Screen Reader Texts
- [ ] implement a function to highlight the active field 
- [ ] labeling control inputs
