### ISSUE TITLE
US15 - Add Icons

### ISSUE THREAD

**Issue by Steffen-Anslinger** [Steffen-Anslinger/DIY-App#22]
## Value Proposition
As a user
I want to have Icons instead of wordings in the navigation
so the navigation is easier to view

## Description

We want to make the navigation look better with icons instead of wordings.

## Acceptance criteria

- [ ] In the navigation bar no words are shown and each item is visible as an icon.

## Tasks

- [ ] replace the wordings with icons
- [ ] add icons to our assets
