### ISSUE TITLE
US14 - Loading Animation / Error handling

### ISSUE THREAD

**Issue by Steffen-Anslinger** [Steffen-Anslinger/DIY-App#23]
## Value Proposition
As a user
I want to have a loading animation and information if something does not load correctly.
so I know what did not work or needs correction.

## Description

We want to give the user a message in case an error appears and an animation if the page is still Loading.

## Acceptance criteria

- [ ] When loading a page i want to see a loading animation
- [ ] If the loading fails I want to see an error message
- [ ] When a feature does not work as expected an error message should be shown to explain the problem.

## Tasks

- [ ] create error message form
- [ ] implement the error messages in all components
- [ ] add the loading animation to the assets
- [ ] add the loading animation to show
