### ISSUE TITLE
US16 - Cloudinary implementation

### ISSUE THREAD

**Issue by MaikBerdelmann** [Steffen-Anslinger/DIY-App#26]
## Value proposition

As a user,
I want to be able to upload image  from the media gallery for the project I create.

## Description

We want to implement an upload function so that the user can use pictures from his own device and don't have to use another website to create a link.

![Image](https://github.com/Steffen-Anslinger/DIY-App/assets/149384055/5ad88191-facb-45f3-afcc-98d0d69cce96)

## Acceptance criteria

- [ ] An upload button is created so that the user can create new entry in the form of input.
- [ ] When the user clicks the upload button, they can select the image from their own device.
- [ ] After uploading, the image can be seen in the new project appearing in the homepage.
## Tasks

- [ ] sign up at Cloudinary 
- [ ] prepare schema for images
- [ ] configure Cloudinary  for the browser
- [ ] save the image in the database

**Comment by uwebury** [comment]
Hello,

nice that you're planning to implement this feature :)

Two small adjustments:
1. The solution is called 'Cloudinary' (no 'N' after 'U').
2. Adding a wireframe in the description would make the user story more descriptive.

Kind regards,
Uwe

**Comment by itsmyrice** [comment]
Looking good !
