### ISSUE TITLE
US17 - Counter Search bar

### ISSUE THREAD

**Issue by MaikBerdelmann** [Steffen-Anslinger/DIY-App#27]
## Value proposition

As a user
I want to see the number of projects displayed after using the search or filter function
in order to know how many projects are being shown out of the total.

## Description

![Image](https://github.com/Steffen-Anslinger/DIY-App/assets/149384055/34f70ffd-b16e-4491-9445-bd701b4620d9)

## Acceptance criteria

- [ ] When performing a search or filter action, a sentence should be displayed above the list of filtered projects stating 'showing X of xx projects, where the X reflects the number of the currently displayed projects.
- [ ] If no projects can be found, the sentence should read 'showing 0 of xx projects.
- [ ] The counter should update in real-time as the user modifies their search/filter criteria.

## Tasks

- [ ] Update the SearchBar and Filter components to include a counter that tracks the number of the displayed projects
- [ ] Create a function that calculates the number of projects currently being displayed
- [ ] Display the results of the counter above the list of filtered projects

**Comment by On-Fi** [comment]
LGTM 👍🏼 
well done :)
