### ISSUE TITLE
US18 - Design Forms

### ISSUE THREAD

**Issue by MaikBerdelmann** [Steffen-Anslinger/DIY-App#28]
## Value proposition

As a user...
I want to have a good overview at the create form and the edit form. They should match the style of the home page. 

## Description

![Image](https://github.com/Steffen-Anslinger/DIY-App/assets/149384055/b4112305-0977-4e76-9428-79f0c54b663f)

## Acceptance criteria

- [ ] implement the app colors
- [ ] edit form and create form should look the same 
- [ ] use minimalistic design 

## Tasks

- [ ] match Button and Link Designs
- [ ] use app colors (color component)
- [ ] make all input fields the same length  
- [ ] reorganise the form fields 
- [ ] redesign the error messages 
- [ ] build components for the designs, so it’s reusable for the edit form and the create form
