### ISSUE TITLE
US18 -  Login Screen / Sign Up

### ISSUE THREAD

**Issue by MaikBerdelmann** [Steffen-Anslinger/DIY-App#29]
## Value proposition

As a user...
I want to login
to be able to update, create and delete projects.

## Description
----------------

## Acceptance criteria

- [ ] There is a login button on the homepage
- [ ] There is a hint on the create page, that you need to login for creation
- [ ] On the detail page you will not see the buttons: edit/delete when you are not logged in.

## Tasks

- [ ] create login with github
- [ ] add hint message
- [ ] update buttons according to login-status
- [ ] use next/authentication
- [ ] link github with vercel and localhost
