### ISSUE TITLE
US2 - Create Page

### ISSUE THREAD

**Issue by JuliaSchw** [Steffen-Anslinger/DIY-App#3]
## Value Preposition
As a user 
I want to be able to add my own projects to the overview
so they appear on the homepage for others as well.

## Description
![Image](https://github.com/Steffen-Anslinger/DIY-App/assets/149384055/3bd1d737-1e14-43a0-899f-c81a12f56672) ![Mittel (User Story 1)](https://github.com/Steffen-Anslinger/DIY-App/assets/149384055/f2e5a41d-d79d-4a5c-b638-e65b693e356b)

## Acceptance Criteria
- [ ] form fields for: title, description, material amount, material name, work step, duration, difficulty
- [ ] field to upload a photo
- [ ] There will be a button on the landing page to reach the create page
- [ ] Clicking the Create button creates a new entry on the homepage and the user is redirected there as well
- [ ] Clicking the Cancel button cancels the entry and we return to the home screen.

## Tasks
- [ ] Create the page pages/create that renders new Projects
- [ ] Create from with the form fields (s.a.)
- [ ] Create a button to reach create page
- [ ] Create a submit button
- [ ] Create a submit event 
- [ ] Render new Project

**Comment by CJAkkuec** [comment]
Nice job!
One thing, though:
>  Clicking the Create button creates a new entry

You've described what happens when you cancel the process, but what happens after hitting create?
Also, how do I get to the create page? Will there be a button on the landing page?

(I know you're trying to avoid writing dependent user stories, but I feel like the first couple of user stories can't quite be accomplished independently.)
