### ISSUE TITLE
US21 - Dark Mode

### ISSUE THREAD

**Issue by MaikBerdelmann** [Steffen-Anslinger/DIY-App#30]
## Value proposition

As a user...
I want to have the option to switch between light and dark mode,
so that i can protect my eyes when i’m in a dark environment.

## Description

--------------

## Acceptance criteria

- [ ] There is a button to toggle between dark and light mode.
- [ ] In the Light Mode, there will be a Light background with dark text. The buttons are Grey and Orange.
- [ ] In the Dark Mode, there will be a Dark background with lighter text. The buttons are Withe and Orange.
- [ ] while pressing the switch button, the user can switch between dark and light mode
- [ ] The toggle button provides visual feedback, to indicate the active mode. Light and Dark Mode are shown with 
        Divergent icons.
- [ ] The App remembers the user's theme preference across sessions.

## Tasks

- [ ] add a switch button to the profile page
- [ ] write a toggle function 
- [ ] create a styling for dark mode
