### ISSUE TITLE
US20 - Profile page

### ISSUE THREAD

**Issue by MaikBerdelmann** [Steffen-Anslinger/DIY-App#31]
## Value proposition

As a user
I want to have a profile page,
so that i can access some user specific information / settings.

## Description

------------------

## Acceptance criteria

- [ ] I have a profile page to navigate to
- [ ] On the profile page the user can see personal data like: Name, Picture
- [ ] On the profile page all of my own projects are rendered.

## Tasks

- [ ] create profile page
- [ ] update navigation component to link to profile page
- [ ] Update projects for profile page to only show my own projects.
