### ISSUE TITLE
US19 - Design Detail Page

### ISSUE THREAD

**Issue by MaikBerdelmann** [Steffen-Anslinger/DIY-App#32]
## Value proposition

As a user...
I want to have a good overview at the Detail Page, which matches the design of the home page, which already exists. 

## Description

-------------------

## Acceptance criteria

- [ ] implement the app colors 
- [ ] use minimalistic design
- [ ] remove distortion of the image 

## Tasks

- [ ] make Image design component
- [ ] change order of the elements
- [ ] use color component

**Comment by Melonexx** [comment]
Seems plausible ✨
