### ISSUE TITLE
US6 - Search bar

### ISSUE THREAD

**Issue by MaikBerdelmann** [Steffen-Anslinger/DIY-App#4]
## Value proposition
As a user 
I want to search through the projects.
In order to find specific projects.

## Description
![Image](https://github.com/Steffen-Anslinger/DIY-App/assets/149384055/8cbf7e4e-5a3a-49df-8e59-8c306473adc7)

## Acceptance criteria
- [ ] Search bar should be displayed in the main page
- [ ] Results should be found while typing
- [ ] Search bar should appear on top of the homepage under the header

## Tasks
- [ ] create a search bar component
- [ ] research fuzzy search
- [ ] implement fuzzy search library

**Comment by CJAkkuec** [comment]
I'd probably add a bit more content to the AC and Tasks.

 > Search bar should be displayed in the main page
 > Search bar should be included to search for projects.

This is basically the same thing twice. What happens if I enter a search term? Do I get a dropdown menu? Does it autocomplete?

>  create a search bar component

![Bildschirm­foto 2024-01-15 um 12 11 19](https://github.com/Steffen-Anslinger/DIY-App/assets/90191489/ca2214d9-2c48-4955-b9e9-47ef3b534cf6)

Please include a dash of "how" in your tasks, such as

> research fuzzy search
> create a SearchBar component
> implement a dropdown menu
> implement fuzzy search library
> ...

Your tasks may look different depending on how you want to handle your search feature.
