### ISSUE TITLE
DS - Update EditForm

### ISSUE THREAD

**Issue by Steffen-Anslinger** [Steffen-Anslinger/DIY-App#41]
## Value proposition

As a developer
I want to have the option to update the Image when editing the projects
to be able to have another image instead.

## Description

--------------

## Acceptance criteria

- [ ] The old image is replaced by the newly uploaded image.
- [ ] After saving only the new image is displayed on the detail page.
- [ ] If no new image is uploaded the old image remains.

## Tasks

- [ ] Update the EditForm with the image.
- [ ] update the "PUT" method.

**Comment by kristinwegener** [comment]
Very nice, I think this could also be a user story because it has a value for the user to be able to change the image. That's up to you :)
