### ISSUE TITLE
US5 - Favourites

### ISSUE THREAD

**Issue by Steffen-Anslinger** [Steffen-Anslinger/DIY-App#5]
## Value proposition
As a user
I want to mark projects as favourites
so that I can find them easier.
I want to be able to see all collected favorites
so that I can have an overview of all of my favorites

## Description
![Image](https://github.com/Steffen-Anslinger/DIY-App/assets/149775085/ae07efa4-30fa-40f7-9517-8352e7ac7d72) ![Image](https://github.com/Steffen-Anslinger/DIY-App/assets/149775085/9429cac2-3998-447e-9564-6da0fbac807b) ![Image](https://github.com/Steffen-Anslinger/DIY-App/assets/149775085/3e3bf6aa-2774-4e23-95e6-b5a583e34a81)

## Acceptance criteria
- [ ] The favourite-button is displayed in each entry in the list view
- [ ] The favourite-button is displayed in the details view
- [ ] Clicking the favourite-button on a non-favourite piece saves it as a favourite
- [ ] Clicking the favourite-button on a favourite piece removes it from favourites
- [ ] All favorite Projects are displayed as a list
- [ ] A navigation link labeled "Favorites" is displayed
- [ ] Each Project image is displayed
- [ ] Each Project title is displayed
- [ ] Each Project is displayed with a favorite-button
- [ ] Each Project is linked to the Details Page

## Tasks
- [ ] Create the component FavouriteButton
- [ ] Create an additional state ProjectInfo to save further information for projects
- [ ] Make the ProjectInfo state globally available for all pages
- [ ] Store the favourite flag in the ProjectInfo
- [ ] Reference projects by slug in the additional state
- [ ] Render the FavouriteButton component in the ProjectPreview and ProjectDetails component
- [ ] Create the page pages/favorites that renders the Projects component
- [ ] Use data from the ProjectsData state to filter for all favorite art pieces
- [ ] Pass the list of all favorite Project via prop projects to the ProjectData component

**Comment by CJAkkuec** [comment]
> As a user
> I want to mark projects as favourites
> so that I can find them easier.
> I want to be able to see all collected favorites
> so that I can have an overview of all of my favorites

Veeeeery strictly speaking, this should be one sentence.

> As a user
> I want to mark projects as favorites and add them to their own overview page
> so that I can find them more easily.

I oftentimes consider an "and" in a user story a sign that you're trying to squeeze two features into one, but I think in this case it's not an issue.

All good. 🚀
