### ISSUE TITLE
US3 - Navigation

### ISSUE THREAD

**Issue by Helenanguyen2023** [Steffen-Anslinger/DIY-App#6]
## Value proposition
As a user
I want to navigate through the app with a menu
so that I can easily navigate to every page.

## Description
![Mittel (User Story 3)](https://github.com/Steffen-Anslinger/DIY-App/assets/149719575/ce4b857e-b6ad-4bb5-93f7-98a5893c4bbb)

## Acceptance criteria
- [ ] the navigation bar should be displayed on the bottom of the page
- [ ] By clicking “Home” you will get redirected to the homepage
- [ ] By clicking “Create” you will get redirected to the create page

## Tasks
- [ ] create navigation component using the next/link component
- [ ] add home and create to the navigation bar
- [ ] link to the respective pages 
- [ ] delete the create Button on the landing page
- [ ] create layout component

**Comment by CJAkkuec** [comment]
Nice job, just a couple of notes ...

> As a user I want to navigate through the app so I can switch pages.

You need also include the interactive process to the AC, like
> Clicking Home or Create navigates the user to the respective pages

The tasks might also benefit from just a hint more detail, such as including mention of the next/link component for example, seeing as how the developer is advises to use a very specific component to handle routing.
