### ISSUE TITLE
US7 - Edit Function

### ISSUE THREAD

**Issue by MaikBerdelmann** [Steffen-Anslinger/DIY-App#7]
## Value proposition
As a user...
I want to be able to edit existing projects
In order to adjust or update my project entries

## Description

![Image](https://github.com/Steffen-Anslinger/DIY-App/assets/149384055/ed71fdb9-1c67-4ce1-a3e6-dfb43e28bf35) |  ![Image](https://github.com/Steffen-Anslinger/DIY-App/assets/149384055/e8d9c55d-84fe-41d5-a441-9c8eae22ba89)

## Acceptance criteria
- [ ] On the entries details page is an edit button
- [ ] By clicking the edit button the user can adjust the pre filled entry details
- [ ] In edit mode there is displayed a save button and a cancel button 
- [ ] The save button saves the new data and shows the updated entry details to the user
- [ ] The cancel button cancels the editing process and brings the user back to the previous entries details page without saving any changes.

## Tasks
- [ ] add example data base to MongoDB
- [ ] setup .env.local and .gitignore
- [ ] implement mongoose and Mongo DB
- [ ] setup Schema & Model
- [ ] Create an edit button that switches the view to an edit mode
- [ ] Create a save button that captures the updated data
- [ ] Create a cancel button that cancels the editing process
- [ ] Create a function to modify the Data

**Comment by jantillidie** [comment]
LGTM
