### ISSUE TITLE
US8 - Delete Function

### ISSUE THREAD

**Issue by MaikBerdelmann** [Steffen-Anslinger/DIY-App#8]
## Value proposition
As a user 
I want to be able to delete the projects.

## Description
![Image](https://github.com/Steffen-Anslinger/DIY-App/assets/149384055/a1aa038e-db49-4418-9537-e4c5b918b498)

## Acceptance criteria
- [ ] On the entries details page is an delete button
- [ ] Clicking the delete button the user can erase the project
- [ ] Before it is deleted an alert to confirm or cancel pops up
- [ ] When clicking cancel, the alert disappears and the user stays on the detail page
- [ ] When confirming delete the user is redirected to the homepage

## Tasks
- [ ] Create a delete button that deletes the data
- [ ] Create an alert to confirm deletion or cancel deletion
- [ ] Create a function to delete the Data

**Comment by jore-averbeck** [comment]
LGTM🚀

What happens after deleting the project? Does the user get redirected to the landing page e.g.?
