### ISSUE TITLE
US9 - Add & Delete Buttons for Material List, Instructions

### ISSUE THREAD

**Issue by Helenanguyen2023** [Steffen-Anslinger/DIY-App#9]
## Value proposition
As a user...
I want to be able to add as much materials as needed and be able to delete them if added incorrectly.
I want to be able to add as much steps as needed and be able to delete them if added incorrectly.
## Description
![Image](https://github.com/Steffen-Anslinger/DIY-App/assets/149719575/3d7803c9-12fb-422b-9c36-086c9ffe9544)  ![Image](https://github.com/Steffen-Anslinger/DIY-App/assets/149719575/5869b4c4-7d57-4e70-a9ba-f5f48bc23ec6)
## Acceptance criteria
- [ ] By clicking the add button 2 new form fields (amount & name) to add materials appears.
- [ ] Each material gets a delete button to delete the entry.
- [ ] By clicking the delete button the amount and name is deleted.
- [ ] By clicking the add button a new form field for steps appears.
- [ ] By clicking the delete button step is deleted.
## Tasks
- [ ] Create the add button (+)
- [ ] Create the delete button (-)
- [ ] Update the Project by submitting data
- [ ] Create the delete button (-)
- [ ] Update the Project by submitting data
- [ ] Add multiple form fields
